### ISSUE TITLE
Unhandled Exception: SocketException: Failed host lookup: 'itunes.apple.com' (OS Error: No address associated with hostname,

### ISSUE THREAD

**Issue by srihariash999** [amugofjava/podcast_search#1]
I am getting this error after using the example provided. I have checked for internet connection of my device and it seems this library is the only one having issues.

**Comment by amugofjava** [comment]
Hi,

It sounds like your device cannot lookup the iTunes server. Can you try this link in the browser on your device and see if you get any results back or if this errors too:

https://itunes.apple.com/search?term=android

Do you know if the other libraries you have tried also use iTunes for searching?

Thanks.

**Comment by srihariash999** [comment]
Sorry for this. Somehow, my app build was stuck in a bad state and was not able to access the internet. Flutter clean and flutter run again, fixed this issue. Closing.
