### ISSUE TITLE
Podcast parser is using item level <author> tag as the channel author

### ISSUE THREAD

**Issue by amugofjava** [amugofjava/podcast_search#10]
The RSS parser is looking for either an `<author>` or `<itunes:author>` tag in the RSS feed as the channel author; however, `<author>` is an item level tag which can result in the wrong author begin returned for the podcast.

To reproduce this, load a podcast that uses item level authors such as 'What Is Money?':

https://feeds.simplecast.com/MLdpYXYI

**Comment by amugofjava** [comment]
Thanks @MaxHillebrand - should be an easy one to fix.

**Comment by amugofjava** [comment]
Have change to just use itunes author tag. Will review other author tags (like Google Play) at a later date.

<img width="480" src="https://user-images.githubusercontent.com/5526902/133287615-acd582f6-009b-4b96-a9f4-2d571ae9a952.png"/>

**Comment by MaxHillebrand** [comment]
Thank you @amugofjava, awesome to see underlying infrastructure improve! That's why free software wins.  :black_heart:
