### ISSUE TITLE
How to get the feed guid from Podcast.loadFeed result?

### ISSUE THREAD

**Issue by arnab** [amugofjava/podcast_search#15]
See the [Podcast Feed GUID spec](https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#guid).

The [`Podcast.loadFeed`](https://github.com/amugofjava/podcast_search/blob/e0d03bc7bb74ca8863319b85bed8a9b6ece672c4/lib/src/model/podcast.dart#L71) method returns a [`Podcast`](https://github.com/amugofjava/podcast_search/blob/e0d03bc7bb74ca8863319b85bed8a9b6ece672c4/lib/src/model/podcast.dart#L23-L66) object, which does not seem to have any `guid` property.

How can we use this library to get to the `guid` from the RSS feed of a Podcast?

**Comment by amugofjava** [comment]
The `guid` tag was added in phase 3 of the Podcast namespace and I am still implementing phase 2 tags in `podcast_search` so `guid` has not been implemented yet.

`guid` is a simple tag, so I can bring its implementation forward if you need it in your project?

**Comment by arnab** [comment]
That would be awesome indeed (getting it added quickly). 

Meanwhile - do you recommend any workarounds (just parsing them RSS feed with a general purpose parser)?
