### ISSUE TITLE
Null-safety migration

### ISSUE THREAD

**Issue by ripetrescu** [amugofjava/podcast_search#9]
Is there any plan to migrate to the new null-safety dart? Thanks!

**Comment by amugofjava** [comment]
Hi @ripetrescu,

Yes, I do plan to migrate to the new null safety and I have begun working on this. Thanks.

**Comment by ripetrescu** [comment]
Hi,

Thank you. Looking forward for this update.

Best,
Rares

**Comment by ripetrescu** [comment]
Sorry, I wrongly "closed" this issue :)

**Comment by ripetrescu** [comment]
Hi @amugofjava

I know you are busy, but do you have any updates on this? :)

Thanks you!

**Comment by amugofjava** [comment]
Hi @ripetrescu,

Yes, sorry it's taking me so long. I wanted to review all the code and reduce the number of nullable items rather than just letting the migration tool run and make everything either `?` or `|`. I have pushed a new branch for the null-safety work so you can see where I am. I have made some manual changes, run the migration tool and all unit tests pass. If you have any comments or feedback that would be great.

**Comment by ripetrescu** [comment]
@amugofjava just checked on my project using the feature/null-safety branch and so far so good. :)

Thank you!

**Comment by amugofjava** [comment]
That's great. Once I have completed my testing, and if all is OK, I'll push to `master` and a new package to pub.dev.

**Comment by amugofjava** [comment]
Hi @ripetrescu,

How are you getting on with the null safe version of podcast_search? Everything still working OK? Thanks.

**Comment by Nirajn2311** [comment]
Hi, any update on this?

**Comment by srihariash999** [comment]
@amugofjava  it is one or two specific podcasts as far as I can tell. But they almost always do.

'The Ben shapiro show' is one example. So might this be an issue from itunes?

**Comment by amugofjava** [comment]
Hi @srihariash999,

The issue with this show is that the RSS feed URL is missing from the iTunes search result. If I repeat the search using PodcastIndex I get the feed & episodes. Bit odd - not sure why the feed would be missing from iTunes. Do you have a few more examples I could try to see if this is the same issue for all of them?

Digging around I can see several comments about iTunes API missing the RSS feed in some results. Not sure if this is a glitch or a result of the new Apple Connect and all its problems.

**Comment by srihariash999** [comment]
@amugofjava  I was haphazardly viewing random ones and there was one more. But i dont remember the name sorry, I'll let you know if i find it again.

**Comment by srihariash999** [comment]
@amugofjava  Found another one called 'Podcast | Matt Walsh'   which is giving an error. But I suspect this is a diffrent story.

This one (for reference)

![image](https://user-images.githubusercontent.com/30948010/131213234-797915d7-bfe0-457b-9057-81fcee585982.png)

**Comment by srihariash999** [comment]
Hi @amugofjava  I found another with Timeout exception, like the Ben Shapiro one.

This is called **'Femmes puissantes'**.  Hopefully this will also have the same feed missing error.

**Comment by amugofjava** [comment]
Hi @srihariash999,

The Matt Walsh one loads fine for me - what error are you getting?

The 'Femmes puissantes' is the same issue as before: no feed URL. This is the query `podcast_search` is sending to iTunes:

[https://itunes.apple.com/search?term=Femmes%20puissantes&limit=10&explicit=No&media=podcast&entity=podcast](https://itunes.apple.com/search?term=Femmes%20puissantes&limit=10&explicit=No&media=podcast&entity=podcast)

This returns two results and the first is missing feedUrl. 

And the same for La Filière:

[https://itunes.apple.com/search?term=La%20Fili%C3%A8re&limit=10&explicit=No&media=podcast&entity=podcast](https://itunes.apple.com/search?term=La%20Fili%C3%A8re&limit=10&explicit=No&media=podcast&entity=podcast)

This is a bit concerning. I will have to do some more digging into this issue; however, I think I am OK to proceed with getting this release out so I will try and merge to `master` soon and push to pub.dev.

**Comment by srihariash999** [comment]
Instance of 'PodcastFailedException'  

@amugofjava  I am unable to get a message from this exception.

**Comment by amugofjava** [comment]
Could you send me a reproducible example @srihariash999? I haven't been able to reproduce this one so far. Thanks.

**Comment by srihariash999** [comment]
**https://themattwalshblog.com/category/podcast/feed/**      This is the feedUrl I am getting from the podcast that has issues.

` Podcast _podcast =  Podcast.loadFeed(url: feedUrl);`

I am just calling **loadFeed** on this url. This is in this one podcast, if not reproducible, I think you can ignore this one and merge.

**Comment by amugofjava** [comment]
Thanks @srihariash999. I haven't been able to reproduce this one. I'll keep testing but will go ahead and merge & push to pub.dev.

Thanks for the feedback.
